on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version
      tcastdl:
        required: true
        description: tcastdl URL
      opustags:
        required: true
        description: opustags URL

name: release
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: download
        run: |
         sudo mkdir DL
         sudo curl -s ${{ github.event.inputs.tcastdl }} -o DL/tcastdl-main.7z
         sudo curl -s ${{ github.event.inputs.opustags }} -o DL/opustags.7z
      
      - name: Setup realese
        run: |
          sudo mkdir -p release
          pushd release || exit 1
          sudo cp -r ../DL/*.7z .
          popd || exit 1
          
      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          artifacts: |
            ./release/*.7z
